- src/components/Icons/story/Icons.stories.constants.ts
- src/components/StepBar/StepBar.stories.tsx
- src/components/Wizard/Wizard.scss
Some linter warnings fell through the cracks.
> Release 0.1.1

- .github/workflows/push.yml
> ci: add token to github workflow

- .storybook/theme.js
> feat: add storybook version [skip ci]

- src/components/Tabs/Tabs.module.scss
- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/TabsNav.stories.tsx
- src/components/Tabs/TabsNav.tsx
- src/styles/main.scss
Font was inconsistent between `Tabs` and `TabsNav` - this PR fixes that!
> fix(tabs): inconsistent font

- src/components/Icons/icons/IconCross.tsx
- src/components/Icons/icons/IconQuestionMark.tsx
- src/components/Icons/index.ts
- src/components/InfoTooltip/InfoTooltip.scss
- src/components/InfoTooltip/InfoTooltip.tsx
- src/components/InfoTooltip/index.ts
- src/components/MediaInput/MediaInput.scss
- src/components/MediaInput/MediaInput.stories.tsx
- src/components/MediaInput/MediaInput.tsx
- src/components/MediaInput/index.ts
- src/components/Wizard/Wizard.scss
- src/components/Wizard/Wizard.stories.tsx
- src/components/Wizard/Wizard.tsx
[Wizard setup](https://www.notion.so/rational-nomads/Wizard-setup-e89ce4c065004ea09ee3d789db4b9341)
-----
```
- Feature
```
Missing a few components and some behaviour in existing components required for the Token Launcher project.
Addition of the InfoTooltip, cross and question mark icons and tweaks to Wizard Header to allow rendering of children.
> feat: additional token launcher components

- package.json
- yarn.lock
This should (hopefully) improve DX by making linting automatic.
> chore: configure Husky pre-commit lint + prettify

- src/components/DropdownMenu/DropdownMenu.scss
- src/components/DropdownMenu/DropdownMenu.stories.tsx
- src/components/DropdownMenu/DropdownMenu.test.tsx
- src/components/DropdownMenu/DropdownMenu.tsx
- Increased testing coverage of DropdownMenu.
- Refactored DropdownMenu slightly.
> test(dropdown-menu): increase coverage

- src/components/index.ts
- add media input to components index
> fix: add media input export to components index

- src/components/AspectRatio/index.ts
- src/components/index.ts
Forwards AspectRatio from Radix as a utility wrapper.
> feat: add Radix AspectRatio

- src/components/DropdownMenu/DropdownMenu.scss
> feat(dropdown): proper hover from Figma

- package.json
increment patch "0.11.5" -> "0.11.6" to publish formatting addresses/domains
> chore: increment patch "0.11.5" -> "0.11.6"

- src/components/DropdownMenu/DropdownMenu.tsx
- src/components/Input/Input.tsx
- src/components/SelectInput/SelectInput.module.scss
- src/components/SelectInput/SelectInput.stories.tsx
- src/components/SelectInput/SelectInput.test.tsx
- src/components/SelectInput/SelectInput.tsx
- src/components/SelectInput/index.ts
- src/components/index.ts
[Create SelectInput Component for zUI](https://www.notion.so/rational-nomads/Create-SelectInput-Component-for-zUI-ea881e61993d4d49ba4a59c6160e1e25)
-----
```
- Feature
```
Missing SelectInput component needed for DAO launcher flow.
Addition of SelectInput component.
> feat: add select input

- src/components/Status/Status.module.scss
- src/components/Status/Status.tsx
- fixes lint warnings pushed with Status component 
- resolves ci build error
> fix: resolve lint warnings

- package.json
- src/components/Avatar/Avatar.module.scss
- src/components/Avatar/Avatar.stories.tsx
- src/components/Avatar/Avatar.test.tsx
- src/components/Avatar/Avatar.tsx
- src/components/Avatar/AvatarIconSize.constants.ts
- src/components/Avatar/index.tsx
- src/components/Status/Status.tsx
- src/components/index.ts
- src/styles/_colors.scss
- yarn.lock
[Avatar Component](https://www.notion.so/rational-nomads/Avatar-component-5cbedb3121a44409b50a3e3a7e7c32c9)
-----
- Feature
The Avatar component is not available
Integrated the new avatar component
> feat(avatar): avatar component

- src/components/Accordion/Accordion.test.tsx
- src/components/Accordion/Accordion.tsx
- src/components/Avatar/Avatar.tsx
- src/components/Table/Column.test.tsx
- src/components/Table/Column.tsx
- src/components/Table/Controls.module.scss
- src/components/Table/Controls.test.tsx
- src/components/Table/Controls.tsx
- src/components/Table/Grid.module.scss
- src/components/Table/Grid.test.tsx
- src/components/Table/Grid.tsx
- src/components/Table/Message.module.scss
- src/components/Table/Message.tsx
- src/components/Table/Table.module.scss
- src/components/Table/Table.tsx
- src/components/Table/alignments.module.scss
- src/components/Table/index.ts
- src/components/ToggleGroup/ToggleGroup.tsx
- src/components/index.ts
[Associated Jira Task](https://wilderworld.atlassian.net/browse/ZAP-39?atlOrigin=eyJpIjoiOTM0NWZiM2M4NzhhNGY2YjljMGY4NzZhOTQwMzk1NTEiLCJwIjoiaiJ9)
-----
Feature
We only had `AsyncTable`, which wasn't composable enough for our needs.
We now have a bunch of `Table` components which combine to make a properly-styled table.
I am pushing this one through so we can iterate quickly, there's still a couple of things that need done:
- We will need to add more tests.
- We will need to add stories.
- We should switch `AsyncTable` to use `Table` internally.
> feat(table): add modular table components

- src/components/Accordion/Accordion.module.scss
- src/components/Avatar/Avatar.module.scss
Bugfix
We're receiving various lint errors such as:
`79:1  ✖  Unexpected duplicate selector ".Accordion",   no-duplicate-selectors`
No more lint errors
I verified by running storybook locally and comparing the UI behaviour/look against the production storybook. Everything appears to match.
> fix: Fix CSS lint errors

- .storybook/preview.js
- minor changes to resolve the console error and warning below which is happening in the storybook configuration
> fix: resolve minor console errors

- src/components/Icons/story/Icons.stories.tsx
- add list of all icons into storybook, it will make our life easier to find out if the icon exist in zUI
- storybook: https://deploy-preview-94--zui-storybook.netlify.app/?path=/story/data-display-icons--all-icons
> add all icons storybook

- src/components/Badge/Badge.module.scss
- src/components/Badge/Badge.test.tsx
- src/components/StepBar/StepBar.test.tsx
- src/components/TextStack/TextStack.test.tsx
> lint: fix warnings

- src/components/Modal/ModalConfirmation/ModalConfirmation.tsx
extends props from the `DialogProps`
> ModalConfirmation props extends

- src/components/Input/Input.module.scss
- src/components/Input/Input.stories.tsx
- src/components/Input/Input.test.tsx
- src/components/Input/Input.tsx
- src/components/Input/PasswordInput.test.tsx
- src/components/Input/PasswordInput.tsx
- src/components/Input/index.tsx
- src/components/index.ts
Adds a PasswordInput component which renders a password input with a visibility toggle.
> feat: Add PasswordInput

- src/components/Button/Button.scss
Previously a button with the text "button" would render as "BUTTON".
The new behaviour is to capitalize: "button" => "Button"
This was a request made by the design team.
> feat: change button text to capitalize

- src/components/Table/Column.tsx
- src/components/Table/Table.module.scss
- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- Table alignment fixes
- Added a Basic Table story
The fixes should resolve Table Header alignments as well as Cell content alignments.
> fix: table header and cell alignments

- src/components/Input/Input.module.scss
Tweak the sizing of the Input Helper text based on feedback from the design team.
> fix: Update sizing of input helper text

- src/components/Video/Video.module.scss
- src/components/Video/Video.stories.tsx
- src/components/Video/Video.test.tsx
- src/components/Video/Video.tsx
- src/components/Video/index.ts
No video component exists with custom controls.
Video component created with custom controls.
zUI storybook: video/default.
Jira Task
https://wilderworld.atlassian.net/jira/software/c/projects/ZAP/boards/34?modal=detail&selectedIssue=ZAP-184
> feat: video component

- package.json
chore: bump version (`0.20.2`) -> (`0.21.0`)
> chore: bump version (`0.20.2`) -> (`0.21.0`)

- package.json
- src/components/Video/Video.module.scss
- src/components/Video/Video.tsx
This task fixes some positioning and colour issues as part of the following Jira Tasks:
- https://wilderworld.atlassian.net/jira/software/c/projects/ZAP/boards/34?modal=detail&selectedIssue=ZAP-23
- https://wilderworld.atlassian.net/jira/software/c/projects/ZAP/boards/34?modal=detail&selectedIssue=ZAP-24
> fix: video custom controls browser size positioning 

- src/components/Input/Input.module.scss
- src/components/Input/PasswordInput.tsx
- Clicking the show/hide button in the password input would show/hide the text, but the button icon wouldn't change
- On Chrome, autofilling an input would apply a white background
- The button icon changes as per Figma
- Autofilled inputs retain normal styles
> feat: input tweaks

- src/components/Button/Button.scss
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.test.tsx
- src/components/Button/Button.tsx
There was no way to add a start or end enhancer to `Button`.
Can now add a start or end enhancer to `Button` through the `startEnhancer` and `endEnhancer` props.
- Check the `Button` enhancer stories in Storybook
- Run tests for `Button.tsx`
> feat(button): add enhancers

- src/components/Input/Input.stories.tsx
- src/components/Input/SearchInput.module.scss
- src/components/Input/SearchInput.test.tsx
- src/components/Input/SearchInput.tsx
- src/components/Input/index.tsx
`search` `Input` didn't match Figma.
`search` `Input` now matches Figma.
1. Open Storybook
2. Navigate to `Inputs > Search`
3. Check that the component matches [Figma](https://www.figma.com/file/wTOVNZonl9MmEzORwBHDuq/ZERO-Design-System-(zDS)?type=design&node-id=4546%3A36921&t=TObYKB5R5LIbt8S5-1)
> feat(search-input): add component

- src/components/Accordion/Accordion.module.scss
- src/components/Accordion/Accordion.tsx
[Jira Task](https://wilderworld.atlassian.net/jira/software/c/projects/ZOS/boards/33?modal=detail&selectedIssue=ZOS-432)
Design:
Updated styles:
> feat(accordion): update low contrast styles

- src/components/Icons/icons/IconCollapse1.tsx
- src/components/Icons/index.ts
- src/components/Input/SearchInput.module.scss
> Add `IconCollapse1`

- package.json
- src/components/Modal/CloseButton.test.tsx
- src/components/Modal/CloseButton.tsx
- src/components/Modal/index.ts
> feat(close-button): add component

- package.json
> chore: bump minor (`0.25.3` -> `0.26.0`)

- package.json
- chore: bump version (`0.26.0`) -> (`0.26.1`)
> chore: bump version (`0.26.0`) -> (`0.26.1`)

- src/components/ToastNotification/ToastNotification.module.scss
- src/components/ToastNotification/ToastNotification.test.tsx
- src/components/ToastNotification/ToastNotification.tsx
> Update `ToastNofication` component: make `actionTitle` configurable

- src/components/ToastNotification/ToastNotification.test.tsx
- src/components/ToastNotification/ToastNotification.tsx
- add custom classname to toast viewport
- update tests to reflect the change
> feat: add viewportClassName to ToastNotification viewport

- package.json
- chore: bump version (`0.26.3`) -> (`0.26.4`)
> chore: bump version (`0.26.3`) -> (`0.26.4`)

- src/components/IconButton/IconButton.scss
- src/components/IconButton/IconButton.test.tsx
- src/components/IconButton/IconButton.tsx
`IconButton`:
index.ts
- Updated the IconButton component to support a variety of size inputs, both named and numeric.
- Implemented size offsets to ensure icons within the buttons have a consistent visual padding, enhancing UX.
- Addressed edge cases for size inputs, ensuring consistent behaviour across different sizes.
- Refactored the code for improved readability, maintainability, and adherence to best practices.
index.test.tsx
- Refactored the IconButton tests to enhance readability and organisation.
- Grouped tests by concern using nested describe blocks for clarity.
- Added comprehensive tests for both icon and button sizes, ensuring all possible sizes and scenarios are tested.
- Ensured all tests are self-contained and clear in their intent. …
> fix: icon button size ratio enhancements and refinements

- package.json
- chore: bump version (`0.26.5`) -> (`0.26.6`)
> chore: bump version (`0.26.5`) -> (`0.26.6`)

- src/components/DropdownMenu/DropdownMenu.test.tsx
- src/components/DropdownMenu/DropdownMenu.tsx
- src/components/SelectInput/SelectInput.test.tsx
Wraps the DropdownMenu contents in a Portal to match previous versions
> Wrap the dropdown in a Portal

- src/components/Avatar/Avatar.module.scss
- src/styles/_glass.scss
- adds avatar glass inset and shadow
- updates colour of fallback icon
> feat: update avatar styles (redesign)

- src/components/DropdownMenu/DropdownMenu.scss
- src/styles/_glass.scss
- updates text and colours of dropdown menu for the redesign.
The specific styles for the dropdown can be set using the available classnames.
> feat: dropdown styles redesign

- src/components/DropdownMenu/DropdownMenu.scss
- src/components/DropdownMenu/DropdownMenu.tsx
- sets max and min widths to the dropdown menu
- sets gap for menu item label content
> feat: add min width and max width to dropdown menu

- src/components/Modal/Modal.module.scss
- removes min width from the modal
> feat(modal): remove min width

- src/components/SelectInput/SelectInput.module.scss
- src/components/SelectInput/SelectInput.test.tsx
- src/components/SelectInput/SelectInput.tsx
Adds a prop to pass down to the dropdown menu (compact/spacious), to render in the select input dropdown so we can control it's size.
> Add `itemSize` prop to `SelectInput` component

- src/components/Accordion/Accordion.module.scss
- src/components/Accordion/Accordion.tsx
- src/styles/_glass.scss
> Update accordion style as per new design

- src/styles/_glass.scss
Adds a background blur on Modal
> Add background blur on modals

- src/components/Skeleton/override.scss
- Updates the Skeleton loads colour as per figma design [here](https://www.figma.com/file/4umQqRC7Lj95w8U83kK8Je/zDS-Global-Components?node-id=3397%3A12391&mode=dev)
> feat: update skeleton loader colour

- package.json
- chore: bump version (`1.9.2`) -> (`1.9.3`)
> chore: bump version (`1.9.2`) -> (`1.9.3`)

- src/components/Button/Button.scss
- src/components/Button/Button.test.tsx
- src/components/Button/Button.tsx
- src/components/Modal/ModalConfirmation/ModalConfirmation.tsx
- This PR updates the styles/state of the `Button` component following the figma designs.
- Please use the deployment url to view the component on storybook.
Examples of updates:
> feat: button component redesign

- package.json
- chore: bump version (`1.9.3`) -> (`1.9.4`)
> chore: bump version (`1.9.3`) -> (`1.9.4`)

- package.json
chore: bump version (`1.9.4`) -> (`1.9.5`)
> chore: bump version (`1.9.4`) -> (`1.9.5`)

- package.json
chore: bump version (`1.9.5`) -> (`1.9.6`)
> chore: bump version (`1.9.5`) -> (`1.9.6`)

- package.json
- chore: bump version (`1.9.6`) -> (`1.9.7`)
> chore: bump version (`1.9.6`) -> (`1.9.7`)

- src/components/Input/Input.stories.tsx
- src/components/Input/Input.tsx
- src/components/Input/NumberInput.tsx
- src/components/Input/PasswordInput.tsx
- src/components/Input/SearchInput.tsx
- src/components/Input/index.tsx
- implementation for - input components to directly forward ref to input element
> feat: input components to directly forward ref to input element

- package.json
- chore: bump version (`1.9.7`) -> (`1.9.8`)
> chore: bump version (`1.9.7`) -> (`1.9.8`)

- src/components/Input/Input.tsx
Refactoring:
- remove unused input ref from input
> refactor: remove unused input ref from input

- package.json
chore: bump version (`1.9.8`) -> (`1.9.9`)
> chore: bump version (`1.9.8`) -> (`1.9.9`)

- src/components/Avatar/Avatar.module.scss
- src/components/Avatar/Avatar.tsx
- src/components/Input/Input.tsx
- adds prop to handle default group icon
- removes delay from fallback
> feat(avatar): handle group default and remove delay

- package.json
chore: bump version (`1.9.9`) -> (`1.10.0`)
> chore: bump version (`1.9.9`) -> (`1.10.0`)

- package.json
chore: bump version (`1.10.0`) -> (`1.10.1`)
> chore: bump version (`1.10.0`) -> (`1.10.1`)

- package.json
chore: bump version (`1.10.1`) -> (`1.10.2`)
> chore: bump version (`1.10.1`) -> (`1.10.2`)

- src/components/Input/Input.tsx
- src/components/Markdown/MarkdownEditor/MarkdownEditor.tsx
- adds fill to the input alerts as these were missed in previous updates
> refactor: add isFilled flag to input alerts

- package.json
- chore: bump version (`1.10.2`) -> (`1.10.3`)
> chore: bump version (`1.10.2`) -> (`1.10.3`)

- src/components/Avatar/Avatar.module.scss
- src/components/Avatar/Avatar.tsx
- applies transitions to image and fallback for improved ui/ux
> feat(avatar): apply transitions to image and fallback

- src/components/Avatar/Avatar.tsx
- applies delay to fallback for the avatar component
> feat(avatar): apply delay to fallback

- package.json
chore: bump version (`1.10.4`) -> (`1.10.5`)
> chore: bump version (`1.10.4`) -> (`1.10.5`)

- package.json
chore: bump version (`1.10.5`) -> (`1.10.6`)
> chore: bump version (`1.10.5`) -> (`1.10.6`)

- src/components/Avatar/Avatar.tsx
- removes rendering fallback condition
> refactor(avatar): remove rendering fallback condition

- package.json
chore: bump version (`1.10.6`) -> (`1.10.7`)
> chore: bump version (`1.10.6`) -> (`1.10.7`)

- src/components/Avatar/Avatar.module.scss
- src/components/Avatar/Avatar.tsx
- reverts animations to avatar component
> refactor(avatar): revert animation additions to avatar image

- package.json
chore: bump version (`1.10.7`) -> (`1.10.8`)
> chore: bump version (`1.10.7`) -> (`1.10.8`)

- src/components/Avatar/Avatar.module.scss
- src/components/Avatar/Avatar.stories.tsx
- src/components/Avatar/Avatar.test.tsx
- src/components/Avatar/Avatar.tsx
- applies timing logic to fallback delay and adds fade in animations to image and fallback elements
- removes logic/code no longer required
> feat(avatar): apply timing logic to fallback delay and add fade in animations

- package.json
- chore: bump version (`1.10.8`) -> (`1.10.9`)
> chore: bump version (`1.10.8`) -> (`1.10.9`)

- src/components/Alert/Alert.module.scss
- src/styles/_glass.scss
Updates the colour and background colour of the info variant.
Adds a mixing (active background) to glass styles.
> feat(info-alert): update colour and background colour of info variant

- package.json
- chore: bump version (`1.10.9`) -> (`1.11.0`)
> chore: bump version (`1.10.9`) -> (`1.11.0`)

- package.json
- chore: bump version (`1.11.0`) -> (`1.11.1`)
> chore: bump version (`1.11.0`) -> (`1.11.1`)

- package.json
- chore: bump version (`1.11.1`) -> (`1.11.2`)
> chore: bump version (`1.11.1`) -> (`1.11.2`)

- src/components/Input/Input.module.scss
- src/components/SelectInput/SelectInput.module.scss
- border colour change.
- fix joltiness.
- apply active colour when dropdown is open.
- text ellipsis on input.
> feat(select-input): border and inset redesign

- package.json
chore: bump version (`1.11.2`) -> (`1.11.3`)
> chore: bump version (`1.11.2`) -> (`1.11.3`)

- package.json
chore: bump version (`1.11.3`) -> (`1.11.4`)
> chore: bump version (`1.11.3`) -> (`1.11.4`)

- package.json
- chore: bump version (`1.11.4`) -> (`1.11.5`)
> chore: bump version (`1.11.4`) -> (`1.11.5`)

- package.json
chore: bump version (`1.12.0`) -> (`1.13.0`)
> chore: bump version (`1.12.0`) -> (`1.13.0`)

- package.json
- src/components/Lightbox/Lightbox.module.scss
- src/components/Lightbox/Lightbox.stories.tsx
- src/components/Lightbox/Lightbox.test.tsx
- src/components/Lightbox/Lightbox.tsx
- src/components/Lightbox/index.ts
- src/lib/hooks/useEscapeManager.test.tsx
- src/lib/hooks/useEscapeManager.tsx
- yarn.lock
- adds lightbox component and escape manager
> feat(lightbox): add lightbox component and escape manager

- src/components/index.ts
- feat(components): export lightbox component
> feat(components): export lightbox component

- package.json
- chore: bump version (`1.15.0`) -> (`1.16.0`)
> chore: bump version (`1.15.0`) -> (`1.16.0`)

- src/components/Lightbox/Lightbox.tsx
- add copy image fallback handling for non-supported clipboard media types
> feat(lightbox): add copy image fallback handling for non-supported clipboard media types

- package.json
- chore: bump version (`1.16.0`) -> (`1.17.0`)
> chore: bump version (`1.16.0`) -> (`1.17.0`)

- src/components/Lightbox/Lightbox.tsx
- copy all image formats to png
> fix(lightbox): copy all image formats to png
