src/components/LoadingIndicator/LoadingIndicator.stories.tsx, src/components/StepBar/StepBar.stories.tsx, src/components/StepBar/StepBar.tsx, src/components/Switch/Switch.stories.tsx, src/components/Switch/index.tsx, src/components/Wizard/Wizard.stories.tsx
[Reconcile Token Launcher design components](https://www.notion.so/rational-nomads/Reconcile-Token-Launcher-design-components-3e1014acc59c41658aecc423d086765a)
-----
```
- Feature
```
- In some instances, the components needed for the coming Token Launcher work are either not present in Storybook or the component is not clearly visible and customizable.
- Fixed stories for LoadingIndicator, Switch and Wizard by wrapping in StoryCard's to make children visible and adding control bindings so we can check custom behaviour.
- Addition of default story for StepBar.
- Fixed bug in StepBar when trying to access title of step when steps list length is 0.
- Added missing id prop to Switch component.
=> feat: reconcile token launcher components and fix stories

src/components/Modal/Modal.module.scss, src/components/Modal/Modal.tsx, src/styles/_colors.scss, yarn.lock
- Removes old CSS-in-JS styling from the `Modal` component.
- Adds `Modal.module.scss` for styling
=> refactor(modal): remove CSS-in-JS [skip ci]

.eslintrc, src/components/Modal/Modal.test.tsx, yarn.lock
Added tests for `Modal`:
- should render string trigger as a button
- should render ReactNode trigger as a ReactNode
- should render children in Radix Content primitive
- should not render Trigger when trigger prop is undefined 
- should apply className prop to Content
- should apply Radix DialogProps to the Radix DialogRoot
- should not render Trigger as a child of Portal
- should render Overlay and Content in Portal with correct nesting
=> test(modal): improve coverage

src/components/Icons/icons/IconAttachment.tsx, src/components/Icons/icons/IconPaperclip.tsx, src/components/Icons/index.ts, src/components/Icons/story/Icons.stories.constants.ts
In zOS we need an attachment icon which we think it's good to start using zUI.
how it looks :
Can you please review it
=> Feat: add attachment icon

src/components/GridCard/GridCard.stories.tsx, src/components/GridCard/templates/NFT.test.tsx, src/components/GridCard/templates/NFT.tsx
- updated NFT template to take a `button` prop that can be passed down, or, not included if required
=> refactor(GridCard/templates): update NFT template to take optional button prop

src/components/SkeletonText/SkeletonText.tsx, src/lib/types.ts
- update 'text' prop type to ReactNode. This will prevent error when passing in components such as `ArrowLink` etc
=> refactor: update text stack prop type to take react node

src/components/AsyncTable/Placeholder.tsx, src/components/AsyncTable/Table.tsx
[Notion Task](https://www.notion.so/zerotech/4985d8ec0c2f4eb4860678eec483e6f6?v=40a33a299f3541f18ec40fbf914ba46f&p=39a32e9780e448ac9b9a7ddffdb2f976&pm=s)
Task: Static table headers should not show a skeleton when table is loading
=> fix: remove loading header placeholders

src/components/Checkbox/Checkbox.module.scss, src/components/Checkbox/Checkbox.stories.tsx, src/components/Checkbox/Checkbox.test.tsx, src/components/Checkbox/Checkbox.tsx, src/styles/_colors.scss
[Advance Checkbox](https://www.notion.so/rational-nomads/Advanced-Checkbox-component-4294de3c18f2468e975a24c57db257c8)
-----
- Feature
Advance checkbox is not available
Implemented the advance checkbox inside the checkbox component
=> feat(checkbox): advance checkbox

src/components/GridCard/GridCard.module.scss, src/components/GridCard/GridCard.tsx
`GridCard` images would flicker while loading
https://user-images.githubusercontent.com/12437916/224830400-ac4f9518-9acf-42aa-b0e0-0801ea019dc6.mov
`GridCard` was showing a `Skeleton` when `imageSrc` was `undefined`. It would render a `Skeleton`, then would flick to `Image`, which also renders a `Skeleton` until `imageSrc` has loaded. This means it would render one `Skeleton`, then change to another `Skeleton`, before ultimately showing the image.
`GridCard` images don't flicker while loading.
I basically just removed the `Skeleton`, and let `Image` handle `undefined` since it was built for that purpose. 
https://user-images.githubusercontent.com/12437916/224830628-987a58cb-0641-438b-afb2-9186e54d7f95.mov
1. Link to NFTs
2. Navigate the subdomain table on grid view
I also did a tiny …
=> fix(grid-card): flicker on image load

src/components/Input/PasswordInput.tsx
Previously if you embedded the PasswordInput into a form then clicking the 'eye' toggle would submit the form.
Clicking the 'eye' toggle no longer submits the form and just toggles the password viewability.
Embed this input in a form and click the eye. Note the form does not submit.
=> fix: prevent password input from submitting forms

package.json
- chore: bump version (`0.20.0`) -> (`0.20.1`) 
- to publish table header alignments
=> chore: bump version (`0.20.0`) -> (`0.20.1`)

src/components/Button/Button.tsx
Previously the button itself wasn't actually disabled (i.e., the `disabled` attribute wasn't set on the rendered node). We were manually preventing onPress events by checking the disabled flag. But, this means that buttons inside forms would still submit the form when hitting enter.
We now set the `disabled` attribute on the `button` node so.
Render the button with `isDisabled={true}` and verify that the HTML node has `disabled` set.
=> fix: Use the disabled attribute for Button rather than our own handling

package.json, src/components/Video/Video.module.scss, src/components/Video/Video.test.tsx, src/components/Video/Video.tsx, src/components/index.ts
Container styles are causing breaks on parent components in zApps.
- fix container styles and pass classNames
- bump zUI version (`0.21.0`) -> (`0.21.1`)
Breaks caused:
Some additions: (This isn't the final color)
https://github.com/zer0-os/zUI/assets/39112648/18fd5956-6bc4-48d7-b90b-8693d576370e
=> fix: video container styles

package.json, src/components/ToastNotification/ToastNotification.module.scss, src/components/ToastNotification/ToastNotification.stories.tsx, src/components/ToastNotification/ToastNotification.test.tsx, src/components/ToastNotification/ToastNotification.tsx, src/components/ToastNotification/index.ts, src/components/index.ts, yarn.lock
- toast notification component with animation.
https://github.com/zer0-os/zUI/assets/39112648/eff8a73f-fb7c-4222-ad15-dcd86fcc67c5
- use the zUI deployment preview
- I have used the modal component in the toast story to highlight the intended behaviour of the toast (as an example)
=> feat: add toast notification component

package.json
- chore: bump version (`0.21.3`) -> (`0.22.0`) (for publishing)
=> chore: bump version (`0.21.3`) -> (`0.22.0`)

src/components/Modal/Modal.module.scss
[ZOS-348](https://wilderworld.atlassian.net/browse/ZOS-348)
`Modal` overlay opacity was too high (`0.9` instead of `0.7`) and there was no blur effect.
- Reduced `Modal` overlay opacity to `0.7`
- Added a `5px` blur to the `Modal` overlay
- For browsers which don't support blur, set `Modal` overlay opacity to `0.85`
Open a modal, check the overlay matches Figma.
[ZOS-348]: https://wilderworld.atlassian.net/browse/ZOS-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: modal background opacity + blur

src/components/IconButton/IconButton.test.tsx, src/components/IconButton/IconButton.tsx, src/components/Input/PasswordInput.test.tsx, src/components/Input/PasswordInput.tsx
When using `PasswordInput` inside the `zOS` login form, the show/hide button would be pressed on enter, rather than the `form` submit button. This is because a `button` `type` was not specified for `IconButton`. This also means that any `form` with an `IconButton` inside it wouldn't submit on enter.
- Added a `button` `type` property to `IconButton`
- Set `type` to `type={'button'}` by default
- Added tests to make sure the `type` stays `button`
- Add `PasswordInput` to a `form`
- Add a submit `button` to the `form`
- Type a password input, and hit enter
At this point, the `form` `onSubmit` should have been called, rather than the show/hide button `onClick`.
Did a tiny amount of refactoring while I had these files open - you'll see it outlined in the commit history.
=> fix: `PasswordInput` should not fire `onSubmit` of containing `form` 

src/components/ToastNotification/ToastNotification.module.scss, src/components/ToastNotification/ToastNotification.tsx
Removes a global style override of all buttons that changed how buttons were sized. Note that default buttons are rendered with box-sizing->border-box. In general, I don't think we want global overrides happening within specific component stylesheets. With bug:
Returned to previous rendering:
=> fix: Remove global reset of buttons

src/components/Button/Button.tsx
Button component could only have children with type string - meaning an Icon or such element could not be used.
'To add an Icon element to the button label I need to update the Button Component in zUI. In order to be able to render an icon in the button label we need to update the children type in Button from string to ReactNode | string. As a result, an Icon can be rendered as part of the Button label.'
Button component children can now be any ReactNode rather than just a string.
[Related Jira Task](https://wilderworld.atlassian.net/jira/software/c/projects/ZOS/boards/33?modal=detail&selectedIssue=ZOS-356)
=> feat: add ReactNode type to button children prop

package.json
Bumps minor version from `0.22.2` to `0.23.0`. This will trigger an NPM publish!
=> chore: bump minor (`0.22.2` -> `0.23.0`)

src/components/Accordion/Accordion.module.scss
Small iteration - The hover will now have the same effects as the conversation items in the conversation panel. The design for the accordion looks to be out of date.
The background modal colour of the rewards faq modal is currently the same colour as the hover colour currently set for the accordion triggers, meaning that there is no colour indication when hovering over these elements. 
This PR updates the colour of the on hover of the accordion trigger to the same as when the accordion is open.
https://deploy-preview-129--zui-storybook.netlify.app/?path=/story/data-display-accordion--low-contrast
=> fix(accordion): trigger hover and active state colours

src/components/Avatar/Avatar.module.scss, src/components/Avatar/Avatar.test.tsx, src/components/Avatar/Avatar.tsx, src/components/DropdownMenu/DropdownMenu.scss
The reason for this change is so we can use Avatar as the trigger for the DropdownMenu component with an `isActive` style. The `focus-within` styling isn't enough to currently satisfy this, as shown in the recordings below.
The issue we're currently facing (recording below) is because the focus-within pseudo class only applies to an element that has received focus itself, or has a descendant which has received focus. However, when the DropdownMenu opens, the Avatar loses its focus because focus is now given to the dropdown menu.
The solution is to manage a state to track whether the dropdown menu is opened or not, and then conditionally add a class to the Avatar to simulate :focus-within.
Here I have created a state variable called isActive in the Avatar component. This means in the …
=> feat: implement 'isActive' state in avatar component

src/components/DropdownMenu/DropdownMenu.scss, src/components/DropdownMenu/DropdownMenu.stories.tsx, src/components/DropdownMenu/DropdownMenu.test.tsx, src/components/DropdownMenu/DropdownMenu.tsx
The arrow pointer will only be visible if `showPointer` is true, and `alignMenu` is set to center. The reason for this is because the pointer will not line up with the `DropdownMenu` if the alignment is `start` or `end` due to the border radius we have on the `DropdownMenu`. For this case, design would have to provide further input for a solution on how to line up the pointer. As this is not required for our needs right now, I am adding what is necessary for the current requirements.
https://github.com/zer0-os/zUI/assets/39112648/de1415a8-1335-4718-b1c4-bed62fba0c15
Alignment issue that would need to be addressed if we ever require this (using red to highlight):
=> feat: add radix dropdown menu arrow pointer

src/components/Avatar/Avatar.stories.tsx, src/components/Avatar/Avatar.test.tsx, src/components/Avatar/Avatar.tsx
- tab index set as '0' on div container of `Avatar`. As a result, the element is included in the normal tab order and can receive focus when tabbing through the page.
- in some scenarios we want to be able to remove `Avatar` from the normal tab order via the tab keydown. 
- adds prop to set tab index to the desired value for tab order. 
- default tab index is set to `0` to ensure behaviour does not change on current uses of `Avatar` and its tab order i.e. profile avatar. 
- you can run storybook (or go to the deployment link created on this PR), type `Avatar` in the search input and select the `DisabledTabIndex` option/template. Click just above the `Avatar` component and press tab on the keyboard. The `Avatar` should not be outlined/focused like it is when using one of the other story …
=> feat: add tab index prop to avatar component

src/components/IconButton/IconButton.scss, src/components/IconButton/IconButton.stories.tsx, src/components/IconButton/IconButton.test.tsx, src/components/IconButton/IconButton.tsx
When passing `size` to the `IconButton`, the button itself is not sized correctly around the `Icon`. This PR fixes this issue by adding an inline style to the button wrapped around the `Icon` component which uses the `size` prop to determine its `width` and `height`.
Now, in zOS (or zApps), you can pass in a size `large`, `small`, `x-small` or simply a number of pixels i.e. something larger like - `48`, or something smaller like - `12`. 
Example - if `large` is set as the `size` for `IconButton`, the `Icon` svg itself will be `40` in width and height, and the button wrapped around the `Icon` will also have a width of `40` and height of `40`.
Examples:
CUSTOM SMALL (`12` number passed in)
CUSTOM LARGE (`68` number passed in)
`x-small` passed in
`small` passed in
`large` passed in
=> fix: icon button sizing and icon sizing to match

src/components/ToastNotification/ToastNotification.stories.tsx, src/components/ToastNotification/ToastNotification.test.tsx, src/components/ToastNotification/ToastNotification.tsx
- adds radix's duration attribute to handle duration toast notification remains open
- adds test coverage for duration
- updates the toast notification story
https://github.com/zer0-os/zUI/assets/39112648/80e3521c-20ec-4c0f-8c14-90f91a7f882e
=> feat: add ability to increase/decrease toast notification duration

package.json, src/components/DropdownMenu/DropdownMenu.test.tsx, src/components/SelectInput/SelectInput.test.tsx, yarn.lock
Updates the @radix-ui/react-dropdown-menu component to v2.0.6 to resolve performance problems with the previously used version
=> Update the dropdown menu to v2.0.6

src/components/Modal/ModalConfirmation/ModalConfirmation.test.tsx, src/components/Modal/ModalConfirmation/ModalConfirmation.tsx
1. ModalConfirmation now takes an `inProgress` flag. When true the primary button will switch to the loading state.
2. Also changed the cancel button from the primary variant to text to match a little more closely with design
=> feat: tweak ModalConfirmation behaviour

src/components/Input/Input.module.scss, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx, src/components/Input/SearchInput.module.scss, src/styles/_glass.scss
Updates the inset styles of the Input component including the Search Input.
Adds a `_glass` stylesheet.
=> feat: update search input inset styles

src/components/Input/PasswordInput.tsx
- Updates password input icon button size as this was causing input sizing to be slightly off when using in zOS.
The issue in ZOS:
=> feat: update password input icon button size

src/components/Input/Input.module.scss
Add a forced width to the inner `input` element to allow the flex display to size properly
=> Add a width to the inner Input to allow proper sizing

src/components/Avatar/Avatar.module.scss
- Removes border from the `Avatar` status and updates the position as per figma designs.
Before:
After:
=> feat: remove avatar status border and update position

src/components/Avatar/Avatar.module.scss, src/components/Avatar/Avatar.test.tsx, src/components/Avatar/Avatar.tsx
- adds `isRaised` boolean to the `Avatar` props.
This ensures that the raised style is only applied if set.
=> feat: add raised class for avatar

src/components/DropdownMenu/DropdownMenu.scss, src/components/DropdownMenu/DropdownMenu.test.tsx, src/components/DropdownMenu/DropdownMenu.tsx
- applies `compact` and `spacious` styles to the dropdown menu items.
Compact
Spacious
=> feat(dropdown menu items): apply spacing styles to dropdown menu items

src/components/IconButton/IconButton.scss
Updates the default color of the Icon button to `$color-greyscale-transparency-12` as part of the zOS redesign.
=> (redesign) change default color of icon button

src/components/Icons/icons/IconInfoCircle.tsx
- remove stroke width from info circle icon to align with stroke width of other icons
before:
after:
=> feat: remove stroke width from info circle icon

package.json, yarn.lock
Pins the version of `remark-emoji` as higher versions have breaking changes
=> Pin remark-emoji

src/components/Input/Input.module.scss
- adds missing border when input is in error state
=> feat: add input border error state

src/components/Accordion/Accordion.module.scss
**NOTE**: This is a temporary change
Currently we're having issue when using accordion in zOS in the backup-faq modal. You can open a question, but when you "close" it, then the slideUp animation is not working. 
This PR temporarily removes it, until we get the animation working.
=> Remove slide up animation from `Accordion`

src/components/Status/Status.module.scss
=> Update Avatar Status badge 'active' style

src/components/Alert/Alert.module.scss
Removes the set background colour on the different Alert variants. If a filled background is required this can be added where the Alert is being imported. Due to latest design updates, in most cases, the filled background is no longer required.
=> feat(alert): remove background colour

src/components/Alert/Alert.module.scss, src/components/Alert/Alert.test.tsx, src/components/Alert/Alert.tsx
- Decided to add an `isFilled` prop to the alert to improve the handling of background colours for the component. This means that where imported, styles shouldn't need to be applied for the background, but instead the developer can apply the `isFilled` flag
=> feat(alert): apply isFilled prop to improve handling of background colour

src/components/Alert/Alert.module.scss, src/components/Avatar/Avatar.tsx
- updates success colour to the standard highlight colour used for zOS.
=> refactor(alert): update success colour

src/styles/_glass.scss
- override glass background-image and mask for todesktop
=> feat: override glass background-image and mask for todesktop

src/components/DropdownMenu/DropdownMenu.tsx, src/components/SelectInput/SelectInput.tsx
Add menuWidth property for dropdown menu/select input to control width of the dropdown menu. This isn't the ideal solution but will do for now as a quick update to control width of these dropdowns in zos
=> feat: add menuWidth for dropdown menu/select input

package.json
- chore: bump version (`1.14.0`) -> (`1.15.0`)
=> chore: bump version (`1.14.0`) -> (`1.15.0`)

tsconfig.json
The TSConfig had a few extra includes that weren't necessary, causing some extra source map files to be deployed to npm.
=> Fix accidental includes added to tsconfig

src/components/Modal/Modal.tsx
- adds visually hidden title and description to Modal for Radix UI accessibility to prevent console errors and warnings
=> fix(radix/dialog): add visually hidden title and description to Modal for Radix UI accessibility to prevent console errors and warnings

package.json
- chore: bump version (`1.24.0`) -> (`1.25.0`)
=> chore: bump version (`1.24.0`) -> (`1.25.0`)
